
services:
  db:
    image: postgres:latest
    restart: always
    user: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - .env
    expose:
      - 5432
    healthcheck:
      test: [ "CMD", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5
  server:
    build:
      context: .
    command: gunicorn StudentGradeSystem.wsgi --bind=0.0.0.0:8000
    expose:
      - 8000
    env_file:
      - .env
    volumes:
      - static_volume:/app/static
    depends_on:
      db:
        condition: service_healthy
  nginx:
    build: ./nginx
    ports:
      - 1337:80
    volumes:
      - static_volume:/app/static
      - nginx_cache:/var/cache/nginx
    depends_on:
      - server

volumes:
  static_volume:
  postgres_data:
  nginx_cache:
